### ISSUE TITLE
[Feature Request] Add option to view dictionary entries in Wiktionary webpage view

### ISSUE THREAD

**Issue by PopeRigby** [rdoeffinger/Dictionary#103]
Like [this](https://photos.app.goo.gl/n4Vm93PQA92BrUgS6).

**Comment by rdoeffinger** [comment]
There is a link to the matching Wiktionary entry you can follow (for the blue underlined words at least), but of course that only works online.
If you mean for offline, I don't think the logic Wiktionary uses to convert their XML data to that web page is easily available anywhere (and it's different for each language's Wiktionary on top of that), neither in a way that it could be run on a desktop PC or in the app, otherwise I'd have tried doing just that...
