### ISSUE TITLE
updated dictionaries placed in wrong place and not extracted

### ISSUE THREAD

**Issue by landry314** [rdoeffinger/Dictionary#12]
i was using 5.1.3 at the time (just updated now to 5.1.4) when i clicked on the icons next to dictionaries that needed updating... it downloaded all of them but placed them in the /storage/emulated/0/ directory on my internal storage instead of in the quickDic directory right there (which was set at the target in the settings). it also failed to extract them. i did this all myself manually and it is working fine.

i am wondering if the updating feature is not working correctly....

sorry i cant test this with 5.1.4 because all my dictionaries are now updated and i deleted the old ones already.

**Comment by rdoeffinger** [comment]
Hmmm, just to be sure...
The zip files always get downloaded to /storage/emulated/0/ always. Maybe not such a great idea, but that is kind of intentional/known for now.
About the unzip issue, I suspect you should get the same just when downloading new dictionaries, not only when updating.
The problem likely is that with Android 4 (or so), Google made it basically impossible to write to external SD-cards for apps that claim to support Android 4.
The exception is special app-specific directories, which the latest version should tell you the path to when you try to edit the quickDic directory and it detects what you specified isn't usable.
However it also should have told you that the chosen directory isn't writable, even with 5.1.3, so not entirely sure what goes on.
Tell me if you come across any additional information that might help tracking this down.

**Comment by landry314** [comment]
using 5.1.4 i just tried downloading a new dictionary from within the app. it worked properly and went into the default directory... maybe it wasnt set properly by default until i switched it? i dont know.

**Comment by rdoeffinger** [comment]
Downloading multiple dictionaries works usually.
Strange things tend to happen though if you end up downloading the same dictionary multiple times (which does seem possible).
I'll keep my eyes open, but so far I don't think I know enough about this to track it down.

**Comment by rdoeffinger** [comment]
I noticed that when updating you sometimes get a lot of error messages, and the dictionary is still shown as updated. It is however actually updated, which you can see after killing and restarting the app for example.
However that only ever happens to me in the Android 2.3 VM, and I suspect that DownloadManager back then was just badly buggy (I get download finished notifications but the files does not exist yet!).
With the latest release downloading multiple times at least should not be possible, as now pressing download a second time will instead abort the download (the UI is a bit bad though).
Not sure if that will help, but you will have a lot of updates with that release to test :)

**Comment by rdoeffinger** [comment]
Did you switch to the 5.2.1 version? If so, did you experience any issues again or did it go fine this time?
I'm happy to collect any data point on these issues.

**Comment by rdoeffinger** [comment]
Closing due to it working for me and the improvements made might have fixed it.
