### ISSUE TITLE
"About QuickDic..." should be updated

### ISSUE THREAD

**Issue by landry314** [rdoeffinger/Dictionary#13]
in the menu we still see the same old "about" entry which has thad huges's email and the old dead link to his website...

**Comment by rdoeffinger** [comment]
The homepage is broken, and copyright is not updated. Fixed in HEAD though, but there are likely a few more such things, not really much of a priority currently.
However the about entry should have my email address since a long time, and it should also display the correct version since 5.1.2 or so.
Are you sure you still see the old one and you're not by chance running the old app?

**Comment by rdoeffinger** [comment]
Fix for homepage link is f2345d7ae29f2b940054efe0c2e060ee2029dc3e (not yet on master though).

**Comment by landry314** [comment]
no, it says QuickDic 5.1.4 (ID 42) then shows the same old information from 5.0.1.

**Comment by rdoeffinger** [comment]
That about box is stored inside the app, not separately, so no.
The text is unchanged, I didn't really want to change it (in part because it's a pain due to translations, in part because I don't consider it my project yet).
And I forgot to change the homepage.
But as said, I think the email should be mine, I changed that fairly early on.

**Comment by 9662** [comment]
![tmp_screenshot_2015-12-10-02-09-33357030303](https://cloud.githubusercontent.com/assets/13080040/11703880/23a90df8-9ee3-11e5-8f41-7729785dc198.png)

Installed from F-Droid a few hours ago.

**Comment by landry314** [comment]
right, the email is updated, but the link, http://code.google.com/p/quickdic-dictionary/ is dead, as you said. i guess that is the most important thing to fix. why not just add a link to this github page? it is the closest thing this project has to a homepage now...

**Comment by rdoeffinger** [comment]
I think this is fine in the latest version, so I'll close it.
