### ISSUE TITLE
Problem with external Storage on LineageOS 18.1 / Android 11

### ISSUE THREAD

**Issue by DrDustwolf** [rdoeffinger/Dictionary#144]
When I select the folder on the external Storage (microsdxc path: "/storage/4163-1714/Android/data/de.reimardoeffinger.quickdic/files") QuickDic doesn't download the selected dictionaries at all.
I tried on 2 devices with LineageOS 18.1. One is rooted the other one not. So I used the the root file manager "com.github.axet.filemanager" (which I installed via F-Droid) to copy the dictionaries (I first downloaded to the internal storage by selecting the path for the dictionaries to standard folder agian) from "/storage/emulated/0/Android/data/de.reimardoeffinger.quickdic/files" to "/storage/4163-1714/Android/data/de.reimardoeffinger.quickdic/files". I had to use this certain filmemanager since the file manager that comes with LineageOS doesn't shows any files or folders inside "/storage/4163-1714/Android/data". Now I selected again the SD ("/storage/4163-1714/Android/data/de.reimardoeffinger.quickdic/files") as storage folder for the dictionaries.
QuickDic unfortunately now shows that the installed dictionaries are broken.
On the other (not rooted) device I wasn't able to acess the folder on the external storage with a file manager. Since the official file manager (as every other I installed too) shows nothing at all inside "storage/*'SD-Card-name'*/Android/data" since it lacks root access. 

Devices tested:
- Lenovo Yoga Tab 3 Plus LTE YT-X703L (LineageOS 18.1 [rooted] {LineageOS-Version: 18.1-20210316-UNOFFICIAL-YTX703L} [unofficial Build])

- LG V20 H990DS (LineageOS 18.1 [not rooted] {LineageOS-Version: 18.1-20210711-NIGHTLY-h990} [latest official Build])

**Comment by DrDustwolf** [comment]
![Screenshot_20210714-235335_QuickDic](https://user-images.githubusercontent.com/14179460/125734913-9fa3fea7-a62e-4bcb-94e2-b0ce63b42ff1.png)
![Screenshot_20210715-001412_Dateien](https://user-images.githubusercontent.com/14179460/125734914-67cd3516-4b72-4c78-b92b-5faf4735cc9b.png)

**Comment by Hruehle** [comment]
I have the same or a similar problem: Fairphone 3, LineageOS-microG 18.1. As Google restricted the access to the external sdcard I can no longer download die dictionaries into storage/xxxx-xxxx/Android/data/de.reimardoeffinger.quickdic. Fortunately I had a backup of those files and with the help of Total Commander I could copy them and Quickdic recognised them (the internal file explorer and MiXplorer are not able to open storage/xxxx-xxxx/Android/data or .....Android/obb only ...Android/media could be used, but this works not with Quickdic). But as there is no write allowance in this folder, I can nothing change. The map-app OsMand fortunately acceptet storage/xxxx-xxxx/Android/media/... But with Quickdic I had no chance

**Comment by rdoeffinger** [comment]
I am not sure you are all seeing the same issue really, but in commit abd7512d20cd6fba56002a0a7e83cae11a98146c I implemented a modern directory selector that also requests the permissions needed.
However I expect it will still have some rough edges and bugs.
Anyone willing to test it? And if so, what's the best way to get it to you? Play Store, or direct download here, or something else?

**Comment by Hruehle** [comment]
Thank you I'm interested is it possible via dict download?

 

Kind regards
 

Heide Rühle

email: ***@***.***
fon: +49 (172) 3925683

 
 

Gesendet: Donnerstag, 19. August 2021 um 23:07 Uhr
Von: "Reimar Döffinger" ***@***.***>
An: "rdoeffinger/Dictionary" ***@***.***>
Cc: "Hruehle" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [rdoeffinger/Dictionary] Problem with external Storage on LineageOS 18.1 / Android 11 (#144)


 

I am not sure you are all seeing the same issue really, but in commit abd7512 I implemented a modern directory selector that also requests the permissions needed.
However I expect it will still have some rough edges and bugs.
Anyone willing to test it? And if so, what's the best way to get it to you? Play Store, or direct download here, or something else?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rdoeffinger** [comment]
Here is a zip file with the apk that has the changes.
[Dictionary-issue144.zip](https://github.com/rdoeffinger/Dictionary/files/7023262/Dictionary-issue144.zip)

**Comment by Hruehle** [comment]
Thank You! I tried both storage/xxxx-xxxx/Android/data/... and ...Android/media/... Both are found without problem; they function, but as I supposed the download of a dictiionary in storage/xxxx-xxxx/Android/data/.... is not possible, on the other hand in the folder ....Android/media it was no problem at all.

Google restricted/denied the write access of apps in that folder. But the app Total Commander has managed this - no idea how that's the only app who can write in this folder - but for me every thing is perfect, storage/xxxx-xxxx/Android/media/de.reimardoefinger... works very well

 
 

Heide Rühle

email: ***@***.***
fon: +49 (172) 3925683

 
 

Gesendet: Freitag, 20. August 2021 um 19:45 Uhr
Von: "Reimar Döffinger" ***@***.***>
An: "rdoeffinger/Dictionary" ***@***.***>
Cc: "Hruehle" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [rdoeffinger/Dictionary] Problem with external Storage on LineageOS 18.1 / Android 11 (#144)


 

Here is a zip file with the apk that has the changes.
Dictionary-issue144.zip

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hruehle** [comment]
This article deals with the problem - but even that makes some mistakes its not mnt/pass_through/0/emulated/0/Android/data but /mnt/pass_through/0/xxxx-xxxx/Andoid/data

Sorry this is my last remark I won't further bother you

Kind regards

Heide Rühle

email: ***@***.***
fon: +49 (172) 3925683

 
 but

Gesendet: Freitag, 20. August 2021 um 19:45 Uhr
Von: "Reimar Döffinger" ***@***.***>
An: "rdoeffinger/Dictionary" ***@***.***>
Cc: "Hruehle" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [rdoeffinger/Dictionary] Problem with external Storage on LineageOS 18.1 / Android 11 (#144)


 

Here is a zip file with the apk that has the changes.
Dictionary-issue144.zip

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hruehle** [comment]
Sorry nom link to the article: https://androinterest.com/2020/11/30/access-android-data-folder-in-android-11/

 

This article deals with the problem - but even that makes some mistakes its not mnt/pass_through/0/emulated/0/Android/data but /mnt/pass_through/0/xxxx-xxxx/Andoid/data

Sorry this is my last remark I won't further bother you

Kind regards

Heide Rühle

email: ***@***.***
fon: +49 (172) 3925683

 
 but

Gesendet: Freitag, 20. August 2021 um 19:45 Uhr
Von: "Reimar Döffinger" ***@***.***>
An: "rdoeffinger/Dictionary" ***@***.***>
Cc: "Hruehle" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [rdoeffinger/Dictionary] Problem with external Storage on LineageOS 18.1 / Android 11 (#144)


 

Here is a zip file with the apk that has the changes.
Dictionary-issue144.zip

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
