### ISSUE TITLE
Issues with Russian dictionary

### ISSUE THREAD

**Issue by Heineken** [rdoeffinger/Dictionary#30]
Using the DE-RU dictionary from 15/DEC/2015 with Quickdict 5.2.6 I noticed the following issues:
- there are polish words, e.g. some declinations of "Quedlinburg" and above a couple beginning with "pł"
- some words cannot be found via look-up although they are present, try "разме́р", then look up "Größe". Same with мудрость-Weisheit.
- I also saw the German word "Mythologie" on the Russian side, but I can't find it again

**Comment by rdoeffinger** [comment]
They're all fixed already, the next release (whenever that happens) would ask you to update, for now you need to delete and re-download to get the new version.
Not happy that the мудрость-Weisheit one has the same translation multiple times in the list though.

**Comment by Heineken** [comment]
Nice.

**Comment by Heineken** [comment]
There are still words in the Russian dictionary that can't be found via look-up:
шить (nähen)
пла́тье (Kleidung)

**Comment by rdoeffinger** [comment]
Please reopen when you find an issue is not fully fixed.

**Comment by Heineken** [comment]
Couldn't find the reopen button...

**Comment by Heineken** [comment]
ме́льница

**Comment by Heineken** [comment]
село́
большинство́

**Comment by rdoeffinger** [comment]
Thanks, I haven't forgotten about this, but it's nothing trivial and I don't have much time for a deep investigation. I did test that they are still missing with the latest version unfortunately (I made several other fixes to the dictionary generation since).

**Comment by rdoeffinger** [comment]
Ok, the issue is with how words containing ь are sorted (there seems to be something special about it) and Android and regular Java disagree again.
For a quick fix I could hack them up to agree (but not sure what Android does? Ignore it? Java seems to put it at the end of the alphabet. Which is correct?) but I'll probably have to look how to get the Android sorting into regular Java somehow.

**Comment by rdoeffinger** [comment]
Ok, switched the dictionary generation to use ICU, which should match Android more closely.
But it's a bit of a risky change. Would appreciate if you could test the new dictionary for me a while before I upload it.
[DE-RU.quickdic.v007.zip](https://github.com/rdoeffinger/Dictionary/files/1202592/DE-RU.quickdic.v007.zip)

**Comment by Heineken** [comment]
1. большинство́, ме́льница are found
2. мудрость is found now, but 6 times.
3. село́ has no ь, but is found
Nice. Good job, I guess.
No other issues observed so far. Will keep testing.

**Comment by rdoeffinger** [comment]
On "село́ has no ь", yes, but it was affected by the same issue because the entries it was compared against contained it, and the dictionary concluded it has "shot by" it and it wasn't in the dictionary.
(or more technical, a binary search over the index is used, and one wrong comparison can throw that completely off, whether the issue is with the item you search for or just the random entry you compare against)
Anyway, new version released, including a brute-force suppression of duplicate entries.
