### ISSUE TITLE
Lookup sporadically not working

### ISSUE THREAD

**Issue by Heineken** [rdoeffinger/Dictionary#35]
In the Japanese-German dictionary I often, not always, experience the following:
- After pasting a kanji (from AnkiDroid) in the search box nothing happens.
- Workaround: switching to German and back, or typing something before the pasted kanji.

Sorry, it's not easily reproducible as it only happens sometimes. Not right now, of course...

EDIT: Also happens in other dictionaries. I just switched to a dictionary after having entered a word. That word was only looked up after typing something. 

This is reproducible with a search term of two words ("give up") in both English dictionaries (not in FR or ES, though).

**Comment by rdoeffinger** [comment]
Weird, it kind of works for me with "give up", but it has about a 2 second delay.
So I suspect my keyboard is actually triggering some autocomplete even that then triggers the search.
I have no idea how pastes are handled actually, I'll have to keep my eyes open where that code is and why it would behave like that.

**Comment by bertogg** [comment]
I'm having this problem as well, or at least something similar.

If I want to look up a word (e.g. 'house') and I type it letter by letter (h-o-u-s-e), then the results are updated with each letter that I type. However this doesn't happen when I do it immediately after starting the program. In this case there's a quite long delay (10 seconds, or more) before I start to see results. After that all lookups work normally.

This is quite annoying and I don't think it happened with earlier versions of QuickDic (I'm using 5.3.3 for Android).

In case it's relevant, I have 5 different dictionaries installed.

**Comment by rdoeffinger** [comment]
I would need some more details, because I can't reproduce it (at least not reliably).
In particular I am wondering:
- How do you type immediately after starting? On my devices it takes quite some time for the onscreen keyboard to come up. Or is this with a physical keyboard?
- Which cases of "starting the program"? Only when starting it fresh after boot, when starting it after manually stopping it, or also when just switching back to it?
- Do you press enter/search after typing the words? Does it make a difference if you do that?
- Does the program in those cases react to scrolling? Maybe it's just busy loading the dictionary still? (it might not notice the keypresses in that case I guess, though I don't know)

I think I can reproduce something like it, but it only happens when I stop the app first, and it's only noticeable on my slowest device. So I think this is simply ICU taking some time to load its data files. I find it a bit ridiculous how slow it is, but it's the only reasonable way to support so many languages and allow searching them without a specialized keyboard for each.

**Comment by bertogg** [comment]
In my case the app shows up very quickly after I press the icon, and the on-screen keyboard appears immediately after that, so I'd say that it takes 2 seconds or less in total before I can start typing (very fast in my opinion).

At that point I can see the first entries of the dictionary and I can scroll down normally and see the rest. I can even press on the scrollbar on the right side and scroll down to the last entries. And still after that typing text won't update the results. Pressing enter doesn't make any difference either.

Once the app is working fine, if I switch to another one and then back to QuickDic then it reacts normally and I can look up words quickly. If I manually stop QuickDic however then I have to wait those 10 seconds again.

So it seems that QuickDic is indexing the entries so they can be looked up. However I just tried uninstalling all my dictionaries but the smallest one (German-Spanish, 2.2 MB) and it doesn't seem to be any faster. The English dictionary alone is 88 MB and contains 10 times more entries, so I would expect a big difference.

**Comment by rdoeffinger** [comment]
Not sure you really want to know the technical details, but no, it can't be indexing because there is no indexing. The index is stored in the dictionary file, and only loaded in tiny parts and on-demand when needed. All initialization around this is already done by the time something is shown in screen (the index is also needed for scrolling, as the languages a bi-directional an index is needed to know the order in which to show things).
The thing that is loaded in the background and is rather slow is things like how to sort words (e.g. in German, ä is sorted with a, while in Swedish ä is sorted after z) and which how letters can be substituted (e.g. German ä is "equivalent" to ae, German ß can be substituted by ss, Swedish ä and å map to a etc.).
For simple cases like the single-language English dictionary that should be very little data and not take any time, but unfortunately I don't think it is working quite that way and I don't know if it is possible to fix (though I guess an indication that it's still loading should be possible to add at the very least).

**Comment by rdoeffinger** [comment]
Argh! There was actually an optimization to make it do a "best effort" search while all the necessary startup is being done, but the locking was too coarse (a bug I introduced in October last year).
So I am not sure what this means for the original report though, since that was before that problem existed. It might be that the fallback code does not work for kanji...

**Comment by bertogg** [comment]
Hi, I just wanted to confirm that everything works perfectly now in v5.3.4. Thanks!! How can I buy you a beer? :-)
