### ISSUE TITLE
Tag 5.2.9 for fdroid

### ISSUE THREAD

**Issue by RealRancor** [rdoeffinger/Dictionary#41]
https://play.google.com/store/apps/details?id=de.reimardoeffinger.quickdic&hl=de has already 5.2.9 but https://f-droid.org/wiki/page/de.reimardoeffinger.quickdic only 5.2.8 because the new release is not tagged as a release.

**Comment by rdoeffinger** [comment]
In this case I actually forgot about it temporarily, but F-droid is behind a few days intentionally.
The reason is that via the Google Play I have a beta channel, I can easily move between beta and production, and I get a lot more feedback (especially crash reports).
So it gets tested there and then it goes on F-droid (though in rare cases I've done it the other way around, too).
I had the tag locally already, and I've now also pushed it.

**Comment by RealRancor** [comment]
Hey, thank you very much for the explanation.
