### ISSUE TITLE
Rename Default theme to dark theme

### ISSUE THREAD

**Issue by mueller-ma** [rdoeffinger/Dictionary#58]
It would be better to choose between dark and bright theme, not default and bright.
If wanted, I can make a PR

**Comment by rdoeffinger** [comment]
If the dark theme is the default (I am not sure about that, I think my phone runs the bright one even though I don't remember changing it) it still would be nice to indicate which one is the default.
In that case "dark theme (default)" might be better wording, just so people know how to get back to defaults.
Otherwise the only thing against it is that a lot of translations might not be updated for a long time, if ever.
But I guess that's kind of a silly argument, so I'll merge a PR if you create one.
