### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by AlfaOmega33** [rdoeffinger/Dictionary#62]
Hi! Is possible load the last version of your app on F-Droid repo (is stop to 5.3.0)??

**Comment by rdoeffinger** [comment]
I am not involved in or maintain the F-Droid builds.
Please ask F-Droid (I guess their forums?) to trigger new builds (or to re-enable the automatic builds).

**Comment by rdoeffinger** [comment]
To clarify: The original setup I agreed with the person adding it to F-Droid was that pushing tags would trigger new builds.
However that soon failed, because someone had modified the build rules while neither informing him or me.
This issue then seems to have been "resolved" by completely disabling that automatic update mechanism, yet again without informing neither me nor the original author of the F-Droid build rules.
As much as I like F-Droid in principle, I've dealt with enough distributions (Linux/BSD side) that I now for my own sanity simply refuse to work with those that don't make an effort to talk to upstream and get issues fixed PROPERLY.
If someone from F-Droid wants to talk to me and make all this work smoothly, I am here to discuss though.

**Comment by krt16s** [comment]
I am very sorry to hear things a working out so badly. Looking at our git tree, the original submitter's last activity was on December 2015... the same month the app got included. Unfortunately, we have a lot of one-shot-submitters, only a couple stay to maintain the builds. Most of the work is done by 1-2 "global" maintainer, like myself, and sometimes work just stays undone and might be forgotten.

I updated the app from time to time, since automatic updates have been disabled -- looking at the git history because the build broke down as a newer utils version was required, so it was not an actual upstream issue.

There currently is a merge request open at https://gitlab.com/fdroid/fdroiddata/merge_requests/1971 to update the app and re-enable automatic updates. How would you like to proceed:

* Go ahead, and risk it breaking when newer util versions is needed.
* Stay on manual updates, and hope for the current submitter to take maintainership.
* Get more closely involved into maintaing this yourself.
* ... other options?

**Comment by rdoeffinger** [comment]
Hi!
I appreciate that you probably are about as short on time as I am, so thanks for responding.
Maintaining this myself or other solutions that require a continuous effort from me are not really a good option. For the rest, I feel it is more a question for you, how would you like to handle it?
- Just enabling automatic updates is better than nothing as Utils will be rarely updated - but it is risky as it might subtly break
- Originally the idea was to always build against HEAD of Utils - I assume that this was considered undesirable (which I can understand), but it should work fine and not break with auto-updates.
- And alternative to building against HEAD that we discussed was to ALSO tag Utils with the same release tags
- While I still think git submodules create as many problems as they solve, it sometimes is better supported. If it would solve the problem in the most convenient way to you, I'm fine with switching over to making Utils a git submodule.

I want a solution that means minimal effort for both of us long-term (and it is the reason why it bothers me a lot when distributions don't complain to me when my code creates problems for them).

**Comment by krt16s** [comment]
Personally I would go with submodules or building against head. Submodules are easy to setup for us while using head makes our linter scream. I will check with some guys resposnible for the fdroid server tools and report back here. For now I just enabled the automatic updates.

**Comment by rdoeffinger** [comment]
I switched it to a submodule. I don't have a new release tag since, but maybe it's enough for you to update the build config already now? Might be a bit before I make the next release, I have a couple of things to do for that.
One reason among many I do not like submodules is due to such user-hostile defaults as not making --recursive the default for git clone, which makes it a pain if you have to work with people who are not that familiar with git (their motto is obviously "make trivial things as difficult as possible").

**Comment by krt16s** [comment]
Thanks for going through the extra hassles, I am quite aware of the.. shortcommings.. of submodules... sigh. I talked to our devs and  they are not really fond of using head, but at least our linter wouldnt complain when using a specific branch (while still being strongly discouraged). Anyway, now submodules it is.

One last thing: Could I ask you to not use versioncode 81 for the next release, but anything above? I'd like to use 81 internally for setting up the template used for the automatic update.

**Comment by rdoeffinger** [comment]
Sure, I changed it to 82 locally, so hopefully I'll remember to skip 81 for the next release.

**Comment by krt16s** [comment]
Thanks, that helps a lot :).

If anything is broken or updates dont work, feel free to ping me directly.
