### ISSUE TITLE
English Polish dictionary doesn't find 'know'

### ISSUE THREAD

**Issue by ericzolf** [rdoeffinger/Dictionary#66]
I have the English-Polish with English flag. When I start to type ' know', up to the 'o' all is fine, the words shown start with kno, but once I've typed the w, the list jumps from 'knob' to 'L' (exactly "L'Aquila (province) (proper noun)	L'Aquila {f}").

This happens always, even changing dictionary, and, because the word just before "kłąb" is Polish and not English, I suspect a bad formatting of the dictionary. 

Thanks, Eric

**Comment by rdoeffinger** [comment]
I have a workaround that will appear in the next version and eliminate almost all these cases (I think), but a 100% fix takes more effort (starting with writing a checker for the dictionaries, unfortunately since Android uses its own ICU fork that means it needs to run on Android which means it will be slow and be a pain to use) and I think I won't have time.

**Comment by rdoeffinger** [comment]
The current solution seems to work fine and a fixed version is on the store, so I am closing this.

**Comment by ericzolf** [comment]
Looks good to me as well with version 5.4.9. Thanks a lot!
