### ISSUE TITLE
No tag for version 5.3.7 available in Play store

### ISSUE THREAD

**Issue by tomikmar** [rdoeffinger/Dictionary#71]
No tag for version 5.3.7 available in Play store - F-Droid build is outdated.

**Comment by rdoeffinger** [comment]
Thanks for reporting, but that was intentional (even though the delay is a bit longer than I had intended),
5.3.7 basically only contains a workaround for bugs in Samsung's 7.x Android, and a fairly risky one at that.
I did not expect that to be useful to many F-Droid users, especially not considering the risk and given that I don't get any kind of automated feedback if something is wrong.
Now that it seems proven stable and I have additional fixes and improvements I intend to make a release soonish, to also be tagged and thus released to F-Droid.
Do you have any particular interest in having 5.3.7 or are you just reporting because I might have forgotten the tag (it has happened admittedly)?

**Comment by tomikmar** [comment]
I use F-Droid (preferred) and Yalp Store. Yalp shows that QuickDic is ready for update and this is the only reason why I opened this ticket - just a small inconsistency I found.

BTW. Thank you for working on QuickDic.

**Comment by rdoeffinger** [comment]
Tag for 5.3.8 pushed.
