### ISSUE TITLE
Downloadmanager Message "2 files are downloaded" is not removed after error

### ISSUE THREAD

**Issue by k3b** [rdoeffinger/Dictionary#72]
QuickDic version 5.3.8 (91) from fdroid
device android-4.2 tablet, german locale, not rooted
QuickDic-directory /mnt/extsd/quickdic  (directory on external sd card where all apps have write permission)

yesterday i startet downloading 3 dictionaries: de-en, de, en

de-en download finished successfully but battery was nearly empty so i disabled wlan to avoid shutdown

after conecting the tablet with power i reenabled wlan so that download can resume.

since then (8 hours ago) messagebar contains "2 files are downloaded" and the progressbar is frozen.

i have rebooted the tablet, but the message "2 files are downloaded" is displayed again.

I found no way to cancel the download

**Comment by rdoeffinger** [comment]
Normally, a download can be cancelled by pressing the same download button again. If that works across downloads is a bit of a question of luck.
But otherwise neither the notifications nor the failure to resume download has anything to do with this app really - that is all handled by the standard "Download Manager" Android component. Unfortunately that app seems to contain some of the most incompetently written code in Android, and it seems that a lot of vendors like to break it even more for no reason.
In the 5.3.9 version you can via menu entry "manual download" get to the download page and download via some other app.

**Comment by k3b** [comment]
after one week of "still downloading" i killed the download manager, cleared it-s data and then exactly one download through the dl-manager was possible. a second download showed the same symptom. maybe some resources are note freed or it has something to do with my android-4.2. the other dictionaries i loaded via "manual download" which worked without problems. 

on the same a-4.2 device the app download via downloadmanager works well with the fdroid-app-store-app.

**Comment by rdoeffinger** [comment]
I am pretty sure the F-Droid app does not use the DownloadManager app but instead re-implements the whole thing, see: https://gitlab.com/fdroid/fdroidclient/tree/master/app/src/main/java/org/fdroid/fdroid/net
A lot of apps do it, but I find it completely unreasonable for me to re-implement a core OS functionality.
If I could reproduce the issues I could possibly at find a workaround, but nowadays it seems to work ok for me.
Normally the cause is companies like Samsung letting their full software incompetence loose on the DownloadManager app, with the result that it is completely broken, but in 4.2 the original Android version was likely quite buggy as well (but custom ROMs are almost always less buggy - though I don't blame you for not wanting to go that route).
