### ISSUE TITLE
Remove all non-letter character before doing a search

### ISSUE THREAD

**Issue by yegorich** [rdoeffinger/Dictionary#80]
If you enter a word with a stop like "merlin." QuickDic won't find the translation First removing the stop character solves the problem.

**Comment by rdoeffinger** [comment]
I wouldn't want to add arbitrary rules like that, that assume . or similar have a specific meaning.
I also think the problem is rather when searching for a word "B" and the dictionary contains only "A" and "C", the dictionary shows "C". It seems it would be better to show "A" to make it easy to see without scrolling up that the word you want is missing, which I think would just happen to fix this issue as well.

**Comment by rdoeffinger** [comment]
Got a bit more complicated, but I think I finally implemented a good solution.
