### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [rdoeffinger/Dictionary#87]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by rdoeffinger** [comment]
I'm neither a designer nor do I care about that kind of thing, so unless someone else steps up this likely won't happen.

**Comment by moshpirit** [comment]
I like graphic design, so I would gladly help if you want, but current logo is great so I don't know if I should change it that much

**Comment by mueller-ma** [comment]
@moshpirit You could use a "Q" as foreground, the flags as background and drop the white border.

**Comment by moshpirit** [comment]
Right now I don't have this time but if you share with me the original scalable vector image, I can try a couple of designs :)

**Comment by p3732** [comment]
Since I use QuickDic a lot and it looks a bit out of place in modern Android versions, I have personal interest in reviving this thread. I recreated the "flag wall" with some modifications and redid the stylized Q according to the 512x512 image icon version. Since the type of shadow the old logo had does not seem to fit with the "adaptive icon" design, I instead opted for a black outline around the Q. Here is what it looks like:

![logo_suggestion](https://user-images.githubusercontent.com/3109792/70206977-8161f500-1729-11ea-9d18-61176edf4293.png)

Since the Q does not really stand out, I would consider adding a blur and some greying out of the flags (though this might be too strong):

![logo_suggestion_blurry](https://user-images.githubusercontent.com/3109792/70207276-98551700-172a-11ea-8ddf-e021b73db875.png)

The .svg files are here btw https://github.com/p3732/various/tree/master/quickdic_logo

Any thoughts or opinions?

**Comment by rdoeffinger** [comment]
Sorry for the long delay in answering.
Why do you think there's a problem with having a shadow as before?
I think it should be just fine to have a shadow in the alpha channel of the foreground.
The only rules I saw as that you should not have it close to the borders of the image.
I think that would look a lot better than the black outline.
I also think that in your version the flags are much larger? I'd prefer them to be small like currently, so that you can't easily recognize a specific one (and also it makes the Q stand out more since the background is more like "noise").

**Comment by rdoeffinger** [comment]
Oh, I forgot the most important part, to do the code changes and maybe have an app for testing it out, I'd need separate foreground and background images.

**Comment by p3732** [comment]
> Why do you think there's a problem with having a shadow as before?

I read on some Android guidelines that shadows should be treated differently, but I can't really recall anymore. I believe it is because the top layer, in our case the Q, can wiggle around and shadows would make that look weird? I am not, I surely can do a version with a shadow outline.

> I also think that in your version the flags are much larger? 

Could be, IIRC I cramped a lot of them together, but then made it so that no flag appears twice in the normal view.

> and also it makes the Q stand out more since the background is more like "noise").

That is why I added the blur in the second version, so that the flags are still recognizable as such, but the Q stands out against them. I can make them smaller though.

> Oh, I forgot the most important part, to do the code changes and maybe have an app for testing it out, I'd need separate foreground and background images.

I wanted to get feedback on the design first. I believe 512x512px is what Android wants, is that correct?

**Comment by rdoeffinger** [comment]
Sorry again for first being slow and now jumping ahead.
I got a background image from the original author of the icon, and quickly made a version of the app using something I created based on it.
Sorry if I've been wasting any of your time!
I personally quite like it, but I admit I don't necessarily have the best taste :)
[icontest.zip](https://github.com/rdoeffinger/Dictionary/files/4433453/icontest.zip)

**Comment by rdoeffinger** [comment]
Btw I couldn't find any case where the parallax effect (foreground moving different from background) is actually implemented, so I don't know what that looks like.
However the drop shadow is really more of a soft black border anyway, so I think it should be ok.

**Comment by p3732** [comment]
> Sorry if I've been wasting any of your time!

As long as we end up with a modern icon, I am fine with it :D

I like the used icon, but I think it might be a bit over the top in its colorfulness. Adding a transparent layer of grey over the flags might reduce that a bit, but again, your choice.
Also I was wondering why the stylized Q snorkel was dropped, but I don't particulary mind. Overall a huge improvement! :)

**Comment by p3732** [comment]
> Btw I couldn't find any case where the parallax effect 

I guess it depends on the launcher, trebuchet uses it when dragging an icon and I believe in some cases where it wants to put focus to an app, why shaking its icon. It works well with the new icon though and you are right, the shadow is like a soft border.

**Comment by rdoeffinger** [comment]
Thanks for the feedback.
Played around a little bit, here's one to compare with slightly reduced colourfulness and different font.
Background and font are easy to change independently luckily, and I also got the offer to dig out the original font.
I fail to have much of an opinion, so if I'll take any input :)
[icontest2.zip](https://github.com/rdoeffinger/Dictionary/files/4433542/icontest2.zip)

**Comment by p3732** [comment]
> EDIT: the Q needs to go a bit more to the right on this one - hadn't noticed that in quick testing in the emulator - hopefully fixed now

Yes about to say. I solved it by centering the O part of the Q. Otherwise looking good to me :)

**Comment by rdoeffinger** [comment]
Published as 5.5.0 in beta channel.
