### ISSUE TITLE
"alternative spelling" in Hebrew > bug or feature? how to turn off?

### ISSUE THREAD

**Issue by shula** [rdoeffinger/Dictionary#92]
When I write  **חת**
i receive  results for either **חט** or **הת**. It is evident that QuickDic searches for similar sound:

**ט** sounds like **ת**
**ה** sounds like **ח**

This deature could be great IF the first spelling is **not** found.

But instead, the first results shown are the /alternative/ spellings, where in practice the original spelling should be shown first.

Consequently, I can't find the word at all !
type: **חתול**  --> not shown (it's a super popular word).
search in English:
type **cat** --> found: **חתול**, first result, no problems.

**Comment by rdoeffinger** [comment]
This would indicate that the ICU collation considers these two spellings equal.
Working around what ICU considers equal is a bit of a problem.
Though as a quick fix it might be possible to simply ensure that actually equal matches have priority over collation-equal matches, I'll have to check how easy that is to add.

**Comment by shula** [comment]
If it doesn't, is it possible to compare with most basic, simple string match ?
(even as an option / settings)

Thank you!

**Comment by rdoeffinger** [comment]
Things are a bit more complicated than that, since there is the whole searching involved, which needs more than just equality check to be efficient.
However after some digging I am not sure that even is the problem.
It looks actually more like these words might not even exist properly in the dictionary.
I have the suspicion that somehow the dictionary only added the transliterations like khatúl to the index, not the word itself.
However this is rather hard to confirm without knowing the language. If you can check if you can find the words you are looking for by scrolling through the dictionary (or quicker, search for a word that should appear close to the dictionary and then scroll to find the word you actually look for) that might help quite a bit.
(and please quote the entry if you find it)

**Comment by rdoeffinger** [comment]
Well, it turned out to be the same issue as lots of similar reports with other issues.
Released 5.5.1 with new dictionaries which seems to fix this.
